transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 256
  decoder_layer: 6
  decoder_head: 2
  decoder_hidden: 256
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2
  decoder_dropout: 0.2

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5

variance_embedding:
  pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

multi_speaker: True

max_seq_len: 1000

vocoder:
  model: "hifigan"
  speaker: "universal"
  ckpt: "/path/to/hifi-gan/ckpt"

diffusion:
  in_dim: 3
  # special configs for diffspeech
  timesteps: 500
  diff_loss_type: l2
  schedule_type: 'linear'
  max_beta: 0.06

  ## model configs for diffspeech
  diff_decoder_type: 'wavenet'
  dilation_cycle_length: 1
  residual_layers: 10
  residual_channels: 64

  ## normalize range: pitch, energy, duration
  x_max: [1, 1, 1]
  x_min: [-1., -1., -1.]
  clip_denoised: True